### PR TITLE
Job Post Model

### PR DESCRIPTION
**Pull request by RainiWijewantha**

### CODE REVIEW

**Review by kavicastelo — CHANGES_REQUESTED** [review]
is caption means job title? if not add job title property also.
add following properties too.
- educational requitements
- responsibilities
- experience level
- end date
- contact email

**Comment by RainiWijewantha** [comment]
> is caption means job title? if not add job title property also. add following properties too.
> 
> * educational requitements
> * responsibilities
> * experience level
> * end date
> * contact email

Caption means job title. We talked about a process where the login is given with an apply button. So need a contact email?

**Comment by kavicastelo** [comment]
> > is caption means job title? if not add job title property also. add following properties too.
> > 
> > * educational requitements
> > * responsibilities
> > * experience level
> > * end date
> > * contact email
> 
> Caption means job title. We talked about a process where the login is given with an apply button. So need a contact email?

Here is the job posting model neh? We need to add the organization's contact email to the job post if the applicant wants to contact the organization directly.

**Comment by RainiWijewantha** [comment]
> > > is caption means job title? if not add job title property also. add following properties too.
> > > 
> > > * educational requitements
> > > * responsibilities
> > > * experience level
> > > * end date
> > > * contact email
> > 
> > 
> > Caption means job title. We talked about a process where the login is given with an apply button. So need a contact email?
> 
> Here is the job posting model neh? We need to add the organization's contact email to the job post if the applicant wants to contact the organization directly.

Ok. I'll add it.

**Review by kavicastelo — APPROVED** [review]
request changes are approved

**Pull request merged**
